name: Deploy
on: 
  pull_request:
  push:
    brunches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{secrets.TOKEN}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          branch: gh-pages
          folder: storybook-static
          clean: true
          force: false
          clean-exclude: |
            special-file.txt
            some/*.txt
