name: Deploy
# site:
#   use_directory_urls: false
#   siteUrl: https://andrewfedotiuk.github.io/bonkers-ui/
#   site_url: https://andrewfedotiuk.github.io/bonkers-ui/
on: 
  pull_request:
  push:
    brunches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build-storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          cname: https://andrewfedotiuk.github.io/bonkers-ui/
      - uses: rymndhng/release-on-push-action@master
        with:
          tag_prefix: "v"
          release_name: "Release <RELEASE_VERSION>"
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

